### ISSUE TITLE
Fix PNML positioning

### ISSUE THREAD

**Issue by 0x4d** [renew-js/renew-formalism-pt#18]
When importing the generated PNML in an editor such as Renew, element positioning is slightly off.

**Comment by tim-kilian** [comment]
As renew is using different coordinates to position the figures, there is probably some error in the translation of the values.

We should also keep in mind to trim the drawing and translate it to the visible area, like is already happening in the context switch with the simulation environment.

**Comment by tim-kilian** [comment]
In addition, I would open this issue in renew-lib too. Because its not clear what it is.
